### ISSUE TITLE
Fallback to npm if yarn is not available

### ISSUE THREAD

**Issue by dhh** [rails/jsbundling-rails#6]
We default to yarn, and that's fine, but if you don't have that installed, it would be nice to fallback to npm.

**Comment by igas** [comment]
@dhh is there are specific reasons for using yarn? My understanding as rails devs we wanted a lock file, but as npm supports that for a while it'll be good to avoid yarn if possible. It would be even cooler if we could avoid node altogether, as esbuild does not need it, but due to the wrapping in jsbundling-rails we'll still need node.

**Comment by phantomwhale** [comment]
Was this closed because "this should happen now" ? Or closed because it was decided not to implement this ?

Given all the good points made above for supporting `npm` in a yarn-free environment, I had presumed it should be the former, but looking over the documentation and trying it out, I'm starting to presume it's actually the latter.
